export const ROUTES = {
  onboarding: "/onboarding",
  home: "/",
  appointments: "/appointments",
  appointment: (id: string) => `/appointments/detail?id=${encodeURIComponent(id)}`,
  tasks: "/tasks",
  task: (id: string) => `/tasks/detail?id=${encodeURIComponent(id)}`,
  habits: "/habits",
  habit: (id: string) => `/habits/detail?id=${encodeURIComponent(id)}`,
  adhkar: "/adhkar",
  search: "/search",
  more: "/more",
  statistics: "/more/statistics",
  settings: "/more/settings",
  settingsNotifications: "/more/settings/notifications",
  settingsIntelligence: "/more/settings/intelligence",
  settingsSync: "/more/settings/sync",
  settingsPrivacy: "/more/settings/privacy",
  settingsBackup: "/more/settings/backup",
  settingsAbout: "/more/settings/about",
} as const;
