export const ROUTES = {
  signIn: "/sign-in",
  authCallback: "/auth/callback",
  onboarding: "/onboarding",
  home: "/",
  appointments: "/appointments",
  appointment: (id: string) => `/appointments/detail?id=${encodeURIComponent(id)}`,
  tasks: "/tasks",
  task: (id: string) => `/tasks/detail?id=${encodeURIComponent(id)}`,
  habits: "/habits",
  habit: (id: string) => `/habits/detail?id=${encodeURIComponent(id)}`,
  adhkar: "/adhkar",
  search: "/search",
  more: "/more",
  plan: "/plan",
  areas: "/areas",
  area: (id: string) => `/areas/detail?id=${encodeURIComponent(id)}`,
  goals: "/goals",
  goal: (id: string) => `/goals/detail?id=${encodeURIComponent(id)}`,
  reviews: "/reviews",
  achievements: "/achievements",
  assistant: "/assistant",
  statistics: "/more/statistics",
  summary: "/more/summary",
  settings: "/more/settings",
  settingsCalendar: "/more/settings/calendar",
  settingsPrayer: "/more/settings/prayer",
  settingsNotifications: "/more/settings/notifications",
  settingsIntelligence: "/more/settings/intelligence",
  settingsAi: "/more/settings/ai",
  settingsSync: "/more/settings/sync",
  settingsPrivacy: "/more/settings/privacy",
  settingsBackup: "/more/settings/backup",
  settingsAbout: "/more/settings/about",
} as const;
